### ISSUE TITLE
Adjust Sensitivity for Unit Designed for In-Field Setting

### ISSUE THREAD

**Issue by pwdel** [Pro777/sharetrack#12]
Adjust Sensitivity for Unit Designed for In-Field Setting:
1. Adjust sensitivity manually.
2. Find out if there is a way to adjust sensitivity digitally with another type of sensor.
3. Create standardized arduino program to adjust and manually set sensitivity in mean-time.

**Comment by Pro777** [comment]
This issue was moved to jaymyers/electron-code#3
