### ISSUE TITLE
Integrate S3 with Yahoo Weather API, Use Standardized Json Weather Objects

### ISSUE THREAD

**Issue by pwdel** [Pro777/sharetrack#18]
Integrate S3 with Yahoo Weather API, Use Standardized Json Weather Objects

**Comment by Pro777** [comment]
This issue was moved to jaymyers/electron-code#5

**Comment by Pro777** [comment]
This issue was moved to jaymyers/electron-code#7

**Comment by Pro777** [comment]
This issue was moved to jaymyers/electron-code#8
